E_helpdesk_college/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
                  path('', include('desk.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

desk/urls.py
from django import views
from django.urls import path
from .views import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('complain', Complain_data, name='complain'),
    path('insert_complain', login_required(login_url='login')(views.Insert_complain.as_view()), name='insert_complain'),
    path('delete_complain/<int:id>', Delete_complain, name='delete_complain'),
    path('insert_feedback', login_required(login_url='login')(views.Insert_feedback.as_view()), name='insert_feedback'),
    path('delete_feedback/<int:id>', Delete_feedback, name='delete_feedback'),
    path('student', Student_data, name='student'),
    path('feedback', Feed_data, name='feedback'),
    path('login', Login, name='login'),
    path('signup', Signup, name='signup'),
    path('validate', validate, name='validate'),
    path('', Dashboard, name='dashboard'),
    path('about',Aboutus,name='about'),
    path('logout', Logout, name='logout'),
    path('insert_student', Insert_student.as_view(), name='insert_student'),
    path('main',AdminSide,name='main')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

desk/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class User(AbstractUser):
    joindate = models.DateField(default=datetime.date.today())
    enddate = models.DateField(null=True)


class College(models.Model):
    name = models.CharField(max_length=30)
    address = models.TextField(max_length=100)
    city = models.CharField(max_length=20)
    pin_code = models.IntegerField()

    def __str__(self):
        return self.name


GENDER = [('Male', 'Male'), ('Female', 'Female')]


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    enroll_no = models.IntegerField()
    name = models.CharField(max_length=20)
    clg_id = models.ForeignKey(College, on_delete=models.SET_NULL, null=True)
    address = models.TextField(max_length=100)
    gender = models.CharField(max_length=10, choices=GENDER)
    city = models.CharField(max_length=20)
    field = models.CharField(max_length=50)
    semester = models.IntegerField()

    def __str__(self):
        return str(self.enroll_no)

    @staticmethod
    def get_student_by_user(user):
        try:
            return Student.objects.get(user=user)
        except:
            False



CATEGORY = [('Canteen', 'Canteen'),
            ('Ground', 'Ground'),
            ('Com_lab', 'com_lab'),
            ('Faculty', 'Faculty'),
            ('ClassRoom', 'ClassRoom'),
            ('Library', 'Library'),
            ('Garden', 'Garden'),
            ('Parking', 'Parking'),
            ('Clg_bus', 'Clg_bus')]


class Complain(models.Model):
    std_id = models.ForeignKey(User,on_delete=models.CASCADE)
    type = models.CharField(choices=CATEGORY, max_length=20)
    date = models.DateField(auto_now_add=True)
    message = models.TextField(max_length=100)
    img = models.FileField()

    def __str__(self):
        return self.type





class Feedback(models.Model):
    std_id = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    feed = models.TextField(max_length=100)
    date = models.DateField(auto_now_add=True)
    happy = models.BooleanField()
    sad = models.BooleanField()
    
    # def __str__(self):
    #     return self.clg_id

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>Our Team</h2><br>
    <div class="row">
 
       <div class="col-md-6 col-sm-6">
          <div class="team-member">
             <div class="team-img">
                <img src="{% static 'img/neha.jpeg' %}" alt="team member" class="img-responsive">
             </div>
             <div class="team-hover">
                <div class="desk">
                   <h4>Hello World!!</h4>
                   <p>I love to introduce myself as a hardcore Web Designer.</p>
                </div>
                <div class="s-link">
                   <a href="#"><i class="fa fa-facebook"></i></a>
                   <a href="#"><i class="fa fa-twitter"></i></a>
                   <a href="#"><i class="fa fa-google-plus"></i></a>
                </div>
             </div>
          </div>
          <div class="team-title">
             <h5>Neha</h5>
             <span>Frontend Developer</span>
          </div>
       </div>
       <div class="col-md-6 col-sm-6">
          <div class="team-member">
             <div class="team-img">
                <img src="{% static 'img/nandini.jpg' %}" alt="team member" height="450px" class="img-responsive">
             </div>
             <div class="team-hover">
                <div class="desk">
                   <h4>Hello World!!</h4>
                   <p>I love to introduce myself as a hardcore Backend Developer.</p>
                </div>
                <div class="s-link">
                   <a href="#"><i class="fa fa-facebook"></i></a>
                   <a href="#"><i class="fa fa-twitter"></i></a>
                   <a href="#"><i class="fa fa-google-plus"></i></a>
                </div>
             </div>
          </div>
          <div class="team-title">
             <h5>Nandini</h5>
             <span>Backend Developer</span>
          </div>
       </div>
    </div>
 </div><br>

{% endblock %}

templates/admin.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {
  margin: 0;
  font-family: "Lato", sans-serif;
}

.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}

.sidebar a.active {
  background-color: #4CAF50;
  color: white;
}

.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
}

@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
</style>
</head>
<body>

<div class="sidebar">
  <a class="active" href="#home">Home</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
</div>

<div class="content">
  <h2>Responsive Sidebar Example</h2>
  <p>This example use media queries to transform the sidebar to a top navigation bar when the screen size is 700px or less.</p>
  <p>We have also added a media query for screens that are 400px or less, which will vertically stack and center the navigation links.</p>
  <h3>Resize the browser window to see the effect.</h3>
</div>

</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <title>E-Help Desk</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="{% static 'css/footer.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Trirong">
      <link rel="stylesheet" href="{% static 'css/team.css' %}">

      <style>
         h2{
            color:red;
            text-align:center;
            font-style: italic;
         }
         body{
            font-family: Lato, sans-serif;
         }
         .notification {
            background-color: #555;
           color: white;
           text-decoration: none;
           padding: 12px 20px;
           margin-left:190px;
           position: relative;
           display: inline-block;
           border-radius: 2px;
         }
         .notification:hover {
           background: green;
           color:white;
           text-decoration: none;
         }
         .notification .badge {
           position: absolute;
           top: -10px;
           right: -10px;
           padding: 5px 10px;
           border-radius: 50%;
           background: red;
           color: white;
         }
      </style>
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <a class="navbar-brand" href="{% url 'dashboard' %}">E-Help</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item {% block homeactive %}  {% endblock homeactive %}">
                  <a class="nav-link" href="{% url 'dashboard' %}">Home</a>
               </li>
               <li class="nav-item {% block aboutactive %}  {% endblock aboutactive %}" >
                  <a class="nav-link" href="{% url 'insert_complain' %}">Complain</a>
               </li>
               <li class="nav-item {% block contactactive %}  {% endblock contactactive %} ">
                  <a class="nav-link" href="{% url 'insert_feedback' %}">Feedback</a>
               </li>
               <li class="nav-item {% block blogactive %}  {% endblock blogactive %} ">
                  <a class="nav-link" href="{% url 'about' %}">About US</a>
               </li>
<!--              <li class="nav-item ">-->
<!--                  <a class="nav-link" href="#contact">Contact US</a>-->
<!--               </li>-->
               <li><a href="#" class="notification"><span>Inbox</span><span class="badge">0</span></a></li>
            </ul>
            <h4 style="color:white; margin-right:230px;">Hello, {{ user.username }} </h4>
            <a href="{% url 'logout' %}" class="btn btn-danger ">Logout</a>
         </div>
      </nav>

      {% block content %}
      {% endblock %}
    <footer class="site-footer" id="about">
         <div class="container">
            <div class="row">
               <div class="col-sm-12 col-md-6">
                  <h6>About</h6>
                  <p class="text-justify">Students can create their account anytime and free. There are complain facility. Students can make a complain in their college and receive a work then students can give a feedback about complain.</p>
               </div>
<!--               <div class="col-xs-6 col-md-3">-->
<!--                  <h6>Categories</h6>-->
<!--                  <ul class="footer-links">-->
<!--                     <li><a href="http://scanfcode.com/category/c-language/">C</a></li>-->
<!--                     <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>-->
<!--                     <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>-->
<!--                     <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>-->
<!--                     <li><a href="http://scanfcode.com/category/android/">Android</a></li>-->
<!--                     <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>-->
<!--                  </ul>-->
<!--               </div>-->
               <div class="col-xs-6 col-md-4">
                  <h6>Quick Links</h6>
                  <ul class="footer-links">
                     <li><a href="#about">About Us</a></li>
                     <li><a href="#contact">Contact Us</a></li>
                     <li><a href="{% url 'insert_complain' %}">Complain</a></li>
                     <li><a href="{% url 'insert_feedback' %}">Feedback</a></li>
                  </ul>
               </div>
            </div>
            <hr>
         </div>
         <div class="container">
            <div class="row">
               <div class="col-md-8 col-sm-6 col-xs-12">
                  <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
                     <a href="#">Nisit Patel</a>.
                  </p>
               </div>
<!--               <div class="col-md-4 col-sm-6 col-xs-12">-->
<!--                  <ul class="social-icons">-->
<!--                     <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>-->
<!--                     <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>-->
<!--                     <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>-->
<!--                     <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>-->
<!--                  </ul>-->
<!--               </div>-->
            </div>
         </div>
      </footer>
      <script rel="script" src="{% static 'js/form.js' %}"></script>

   </body>
</html>

templates/complain.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <title>Bootstrap Example</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="{% static 'css/footer.css' %}">
      <link rel="stylesheet" href="{% static 'css/openform.css' %}">
      <style>
         h2{
         color:red;
         text-align:center;
         font-style: italic;
         }
         body{
         font-family: Lato, sans-serif;
         }
      </style>
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <a class="navbar-brand" href="{% url 'dashboard' %}">E-Help</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item {% block homeactive %}  {% endblock homeactive %}">
                  <a class="nav-link" href="{% url 'dashboard' %}">Home</a>
               </li>
               <li class="nav-item {% block aboutactive %}  {% endblock aboutactive %}" >
                  <a class="nav-link" href="{% url 'insert_complain' %}">Complain</a>
               </li>
               <li class="nav-item {% block contactactive %}  {% endblock contactactive %} ">
                  <a class="nav-link" href="{% url 'feedback' %}">Feedbacks</a>
               </li>
               <li class="nav-item {% block blogactive %}  {% endblock blogactive %} ">
                  <a class="nav-link" href="#about">About US</a>
               </li>
              <li class="nav-item ">
                  <a class="nav-link" href="#contact">Contact US</a>
               </li>
            </ul>
            <h4 style="color:white; margin-right:230px;">Hello, {{ user.username }}</h4>
            <a href="{% url 'login' %}" class="btn btn-success mr-2">Login</a>
            <button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#signupModal">SignUp</button>
         </div>
      </nav>

<h2 align="center">Complain List</h2>
<table class="table table-bordered">
    <thead class="thead-light">
    <tr>
        <th>ID</th>
        <th>Std_ID</th>
        <th>Type</th>
        <th>Date</th>
        <th>Message</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    {% for i in cm %}
    <tr>
        <td>{{ i.id }}</td>
        <td>{{ i.std_id }}</td>
        <td>{{ i.type }}</td>
        <td>{{ i.date }}</td>
        <td>{{ i.message }}</td>
        <td><button class="open-button btn btn-outline-warning" onclick="openForm()">Accept</button>
                <div class="form-popup" id="myForm">
            <form class="form-container">
                <label for="message"><b>Message</b></label>
                <input type="text" placeholder="Enter Message" id="message" name="message" required>
                <button type="submit" class="btn">Send</button>
                <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
            </form>
                </div></td>
        <td><a href="{% url 'delete_complain' i.id %}" class="btn btn-outline-danger">Reject</a> </td>
    </tr>
    {% endfor %}
</table>

   <script>
function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>
   </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--<div class="container-fluid">-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
   <!-- Indicators -->
   <ul class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
   </ul>
   <!-- The slideshow -->
   <div class="carousel-inner">
      <div class="carousel-item active">
         <img src="{% static 'img/img1.jpg' %}" alt="Los Angeles" width="100%" height="600">
      </div>
      <div class="carousel-item">
         <img src="{% static 'img/img2.jpg' %}" alt="Chicago" width="100%" height="600">
      </div>
      <div class="carousel-item">
         <img src="{% static 'img/img3.jpg' %}" alt="New York" width="100%" height="600">
      </div>
   </div>
   <!-- Left and right controls -->
   <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
   <span class="carousel-control-prev-icon"></span>
   </a>
   <a class="carousel-control-next" href="#myCarousel" data-slide="next">
   <span class="carousel-control-next-icon"></span>
   </a>
</div>
<!--</div>--><br>
<h2>Our Featured</h2>
<hr>
<section id="gallery">
   <div class="container">
      <div class="row">
         <div class="col-lg-4 mb-4">
            <div class="card">
               <img src="{% static 'img/img6.webp' %}" alt="" class="card-img-top" height="185">
               <div class="card-body">
                  <h5 class="card-title">Make Complain</h5>
                  <p class="card-text" style="padding-bottom:24px;">Student's Have To Able to make an any complain to it's college.</p>
               </div>
            </div>
         </div>
         <div class="col-lg-4 mb-4">
            <div class="card">
               <img src="{% static 'img/img7.png' %}" alt="" class="card-img-top" height="185">
               <div class="card-body">
                  <h5 class="card-title">Account</h5>
                  <p class="card-text">Every Student have to make an account in this website and see the all complains and see the all actions on their complain!</p>
               </div>
            </div>
         </div>
         <div class="col-lg-4 mb-4">
            <div class="card">
               <img src="{% static 'img/img4.jpg' %}" alt="" class="card-img-top" height="185">
               <div class="card-body">
                  <h5 class="card-title">Feedback</h5>
                  <p class="card-text" style="padding-bottom:24px;">Every student have to give feedback about their complain!</p>
               </div>
            </div>
         </div>
      </div>
   </div>
</section><hr><br>
<div class="container">
   <h2>Our Team</h2><br>
   <div class="row">

      <div class="col-md-6 col-sm-6">
         <div class="team-member">
            <div class="team-img">
               <img src="{% static 'img/neha.jpeg' %}" alt="team member" class="img-responsive">
            </div>
            <div class="team-hover">
               <div class="desk">
                  <h4>Hello World!!</h4>
                  <p>I love to introduce myself as a hardcore Web Designer.</p>
               </div>
               <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
               </div>
            </div>
         </div>
         <div class="team-title">
            <h5>Neha</h5>
            <span>Frontend Developer</span>
         </div>
      </div>
      <div class="col-md-6 col-sm-6">
         <div class="team-member">
            <div class="team-img">
               <img src="{% static 'img/nandini.jpg' %}" alt="team member" height="450px" class="img-responsive">
            </div>
            <div class="team-hover">
               <div class="desk">
                  <h4>Hello World!!</h4>
                  <p>I love to introduce myself as a hardcore Backend Developer.</p>
               </div>
               <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
               </div>
            </div>
         </div>
         <div class="team-title">
            <h5>Nandini</h5>
            <span>Backend Developer</span>
         </div>
      </div>
   </div>
</div><br>
<h2 id="contact">Get In Touch With Us</h2>
<br>
<div class="container">
   <div class="row">
      <div class="col-lg-12 col-lg-offset-2">
         <form id="contact-form" method="post" action="" role="form">
            <div class="messages"></div>
            <div class="controls">
               <div class="row">
                  <div class="col-md-6">
                     <div class="form-group">
                        <label for="form_name">Firstname</label>
                        <input id="form_name" type="text" name="name" class="form-control" placeholder="firstname" required="required" data-error="Firstname is required.">
                        <div class="help-block with-errors"></div>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="form-group">
                        <label for="form_lastname">Lastname</label>
                        <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="lastname" required="required" data-error="Lastname is required.">
                        <div class="help-block with-errors"></div>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <div class="form-group">
                        <label for="form_email">Email</label>
                        <input id="form_email" type="email" name="email" class="form-control" placeholder="email" required="required" data-error="Valid email is required.">
                        <div class="help-block with-errors"></div>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="form-group">
                        <label for="form_phone">Phone</label>
                        <input id="form_phone" type="tel" name="phone" class="form-control" placeholder="Contact">
                        <div class="help-block with-errors"></div>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <div class="form-group">
                        <label for="form_message">Message</label>
                        <textarea id="form_message" name="message" class="form-control" placeholder="Message for me" rows="4" required data-error="Please,leave us a message."></textarea>
                        <div class="help-block with-errors"></div>
                     </div>
                  </div>
                  <div class="col-md-12">
                     <input type="submit" class="btn btn-success btn-send" value="Send message">
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>
<br>
<!-- Site footer -->
{% endblock %}

templates/feedback.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 align="center">Feedbacks</h2>
<table class="table table-bordered">
    <thead class="thead-light">
    <tr>
        <th>ID</th>
        <th>Std_ID</th>
        <th>Feed</th>
        <th>Date</th>
        <th>Status</th>
        <th>Delete</th>
    </tr>
    </thead>
    {% for i in fd %}
    <tr>
        <td>{{ i.id }}</td>
        <td>{{ i.std_id }}</td>
        <td>{{ i.feed }}</td>
        <td>{{ i.date }}</td>
        {% if i.happy %}
        <td><img src="{% static 'img/yes.png' %}" height="20" width="20" style="margin-left:25px;"></td>
        {% else %}
        <td><img src="{%  static 'img/no.png' %}" height="20" width="20" style="margin-left:25px;"></td>
        {% endif %}
        <td><a href="{% url 'delete_feedback' i.id %}" class="btn btn-outline-danger">Delete</a> </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/insert_complain.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<br>
<h2>Complain</h2>
<!--<div class="container">-->
<!--  <div class="alert-success alert-dismissible">-->
<!--      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>-->
  {% for message in messages %}
      <strong>Success!</strong> {{ message }}
    {% endfor %}
<!--  </div>-->

<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-primary">Submit</button>
</form>
</div><br>

{% endblock %}

templates/insert_feedback.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<br>
<h2>Give Your Feedback</h2>
<div class="container">
  <div class="alert-success alert-dismissible">
<!--      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>-->
{% for message in messages %}
   <strong> {{ message }} </strong>
    {% endfor %}
  </div>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-primary">Submit</button>
</form>
</div><br>

{% endblock %}

templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>Title</title>
      <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
      <link rel="stylesheet" href="{% static 'css/login.css' %}">
      <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <!------ Include the above in your HEAD tag ---------->
   </head>
   <body>
<!--      <div class="fadeIn" id="signupModal" tabindex="-1" aria-labelledby="signupModal" aria-hidden="true">-->
   {% for message in messages  %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message : </strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      {% endfor %}
  <div class="fadeIn modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="signupModalTitle" align="center">SignUp Here</h5>

      </div>
      <div class="modal-body">
  <form action= "/signup" method='POST'>
    {% csrf_token %}
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" id="id_username" name="username" placeholder="Choose a unique username" required>
  </div>

  </div>
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="id_email" name="email" placeholder="name@example.com" required>
  </div>
  <div class="form-group">
    <label for="join">Join Date:</label>
    <input type="date" class="form-control" id="id_joindate" name="joindate"  required>
  </div>
  <div class="form-group">
    <label for="enddate">End Date:</label>
    <input type="date" class="form-control" id="id_enddate" name="enddate" required>
  </div>
  <div class="form-group">
    <label for="pass1">Choose a password</label>
    <input type="password" class="form-control" id="id_password" name="password" placeholder="Choose Your Password" required>
  </div>
       
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
<!--</div>-->

   </body>
</html>